update ns3 to version 3.38
simbricks/ns-3 pull request #1
Opened 2023-07-28 18:39 UTC by marvin71

This pull request updates ns3 to version 3.38. It also renames the `cosim` module to `simbricks`.

2024-05-04 09:12 UTC, jonas-kaufmann requested changes
Overall looks good to me. I've annotated a few locations with commented out code that I suspect we don't need anymore. Further, there are same files that are either basically empty or are just the copied over template. I'd remove these.

Finally, I suggest we run the ns-3's auto-formatter over all files after fixing all of the other stuff. There's still a white-space before the function call operator in many places and ns-3 actually switched away from that format. I'd use a separate commit to introduce the formatting changes after you changed everything else though, otherwise we mix pure formatting changes and truly functional changes.

2024-05-04 09:12 UTC, jonas-kaufmann commented on src/red/model/dev-red-queue-ppp.h
> +  */
Can we remove this code?

2024-05-04 09:12 UTC, jonas-kaufmann commented on src/sequencer/doc/sequencer.rst
This documentation is just placeholder, can we just drop it?

2024-05-04 09:12 UTC, jonas-kaufmann commented on src/sequencer/test/sequencer-test-suite.cc
Throw this out since it's just a copied template?

2024-05-04 09:12 UTC, jonas-kaufmann commented on src/simbricks/doc/simbricks.rst
Also an empty template, remove?

2024-05-04 09:12 UTC, jonas-kaufmann commented on src/simbricks/examples/simbricks-dumbbell.cc
> + * Copyright (c) 2012 University of Washington, 2012 INRIA
Is this copyright header correct? It's dated to 2012

2024-05-04 09:12 UTC, jonas-kaufmann commented on src/simbricks/examples/simbricks-dumbbell.cc
> +  //LogComponentEnable ("TrafficControlLayer", LOG_LEVEL_ALL);
Can we throw this out?

2024-05-04 09:12 UTC, jonas-kaufmann commented on src/simbricks/examples/simbricks-dumbbell.cc
> +  //NetDeviceContainer ptpDev = pointToPointSR.Install (nodeLeft, nodeRight);
Can we throw this out?

2024-05-04 09:12 UTC, jonas-kaufmann commented on src/simbricks/examples/simbricks-dumbbell.cc
> +  //bridgeRight->AddBridgePort (ptpDevRight);
Can we throw this out?

2024-05-04 09:12 UTC, jonas-kaufmann commented on src/simbricks/helper/simbricks-helper.cc
Empty, can we throw this out?

2024-05-04 09:12 UTC, jonas-kaufmann commented on src/simbricks/helper/simbricks-helper.h
This file is empty, throw it out?

2024-05-04 09:12 UTC, jonas-kaufmann commented on src/simbricks/model/simbricks-nicif.h
> +}
Auto-format this, it looks off.

2024-05-04 09:12 UTC, jonas-kaufmann commented on src/simbricks/model/simbricks.h
> +}
Formatting looks off here, run auto-formatter.

2024-05-04 09:12 UTC, jonas-kaufmann commented on src/simbricks/test/simbricks-test-suite.cc
This is just the template copied over. Just remove the file then?

2024-05-04 09:12 UTC, jonas-kaufmann commented on src/traffic-control/model/red-queue-disc.cc
> +    if (m_qAvg >= m_minTh)
Instead of commenting old version out, replace it and remove the comment?

2024-05-04 09:12 UTC, jonas-kaufmann commented on src/traffic-control/model/red-queue-disc.cc
Remove code instead of commenting out?

2024-05-04 09:12 UTC, jonas-kaufmann commented on src/simbricks/examples/simbricks-dumbbell.cc
> + * Copyright (c) 2012 University of Washington, 2012 INRIA
Also now that I saw other files we added, they include our copyright header. @FreakyPenguin Should we change this to our header here?

2024-05-06 12:21 UTC, FreakyPenguin commented on src/simbricks/examples/simbricks-dumbbell.cc
> + * Copyright (c) 2012 University of Washington, 2012 INRIA
I assume that the reason this file has this license header is that we copied it from elsewhere and then made changes. In which case we definitely should not change the copyright header.

2024-05-06 15:00 UTC, marvin71 commented on src/traffic-control/model/red-queue-disc.cc
> +    if (m_qAvg >= m_minTh)
I would rather leave this in there, so that it is easy to see that we changed something there.

2024-05-06 15:00 UTC, marvin71 commented on src/traffic-control/model/red-queue-disc.cc
The same here.

2024-05-06 15:02 UTC, marvin71 commented on src/simbricks/model/simbricks-nicif.h
> +}
#3 changes the SimBricks adapters anyways, so I am not going to reformat this now. But I will do it later after #3 is merged.

2024-05-06 15:03 UTC, marvin71 commented on src/simbricks/model/simbricks.h
> +}
Again no reformat now.

2024-05-06 15:16 UTC, marvin71 commented on src/simbricks/examples/simbricks-dumbbell.cc
> +  //LogComponentEnable ("TrafficControlLayer", LOG_LEVEL_ALL);
I will do this later.

2024-05-06 17:06 UTC, jonas-kaufmann approved these changes
LGTM

2024-05-06 19:49 UTC, merged